"""General Assistant — the platform's navigation agent and router fallback.

LLM-FIRST AND STREAMING: general questions stream token-by-token from the
team's deployment (via ACE's gateway) with the navigation system prompt.
Two deliberate non-LLM answers remain: the access overview (live Casbin-
scoped catalog DATA — never hallucinated) and the pre-creds fallback
template. It is a TERMINAL agent: it never delegates and never re-routes.
"""

from collections.abc import AsyncIterator

from google.protobuf import json_format

from ace_agent_kit import AceCapabilityClient, ContextEnvelope

from a2a.helpers import new_text_message
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events import EventQueue

from .config import AgentConfig, get_agent_config

_ACCESS_KEYWORDS = ("access", "who can", "what can i", "permission", "help me with")


class GeneralAgent:
    def __init__(
        self,
        config: AgentConfig | None = None,
        capabilities: AceCapabilityClient | None = None,
    ) -> None:
        self._config = config or get_agent_config()
        self._capabilities = capabilities or AceCapabilityClient(
            base_url=self._config.ace_base_url
        )

    async def answer_stream(
        self, *, user_input: str, envelope: ContextEnvelope | None
    ) -> AsyncIterator[str]:
        question = user_input.strip()
        if envelope is not None and any(
            keyword in question.lower() for keyword in _ACCESS_KEYWORDS
        ):
            yield await self._access_overview(envelope)
            return

        if envelope is not None:
            streamed_any = False
            try:
                async for token in self._llm_token_stream(question, envelope):
                    streamed_any = True
                    yield token
            except Exception:  # noqa: BLE001 — LLM not configured yet: template fallback
                streamed_any = False
            if streamed_any:
                return
        yield self._fallback(question)

    def _llm_token_stream(
        self, question: str, envelope: ContextEnvelope
    ) -> AsyncIterator[str]:
        deployment = self._config.default_deployment
        system_prompt = self._config.prompt_store.get("system")
        if not deployment or system_prompt is None:
            raise RuntimeError("LLM deployment not configured.")
        return self._capabilities.llm_chat_stream(
            envelope=envelope,
            agent_key=self._config.agent_key,
            deployment=deployment,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt.format(
                        display_name=self._config.display_name
                    ),
                },
                {"role": "user", "content": question},
            ],
        )

    def _fallback(self, question: str) -> str:
        fallback = self._config.prompt_store.get("fallback")
        if fallback is not None:
            return fallback.format(
                display_name=self._config.display_name, question=question
            ).strip()
        return (
            f"[{self._config.display_name}] Ask 'what can I access?' to see the "
            "assistants available to your role."
        )

    async def _access_overview(self, envelope: ContextEnvelope) -> str:
        """Live role-scoped catalog — authoritative DATA, deliberately not
        generated by an LLM."""
        agents = await self._capabilities.accessible_agents(envelope=envelope)
        if not agents:
            return (
                "Your current roles have no assistants assigned yet. "
                "Please contact your administrator to request access."
            )
        lines = [
            f"Based on your roles ({', '.join(envelope.roles) or 'none'}), "
            "you can use these assistants:"
        ]
        for agent in agents:
            owner = f" (team: {agent.team_key})" if agent.team_key else ""
            lines.append(f"- **{agent.display_name}**{owner} — {agent.description}")
        lines.append(
            "If you need something not listed, the owning team can grant access."
        )
        return "\n".join(lines)


class TeamAgentExecutor(AgentExecutor):
    def __init__(self) -> None:
        self._agent = GeneralAgent()

    @staticmethod
    def _envelope_from(context: RequestContext) -> ContextEnvelope | None:
        if context.message is None:
            return None
        metadata = json_format.MessageToDict(context.message.metadata)
        return ContextEnvelope.from_metadata(metadata)

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        async for chunk in self._agent.answer_stream(
            user_input=context.get_user_input(),
            envelope=self._envelope_from(context),
        ):
            await event_queue.enqueue_event(
                new_text_message(
                    chunk, context_id=context.context_id, task_id=context.task_id
                )
            )

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise NotImplementedError("Cancellation is not supported by this agent.")
